#!/bin/bash

nvim +'CocInstall coc-clangd'
nvim +'CocInstall coc-cmake'
nvim +'CocInstall coc-css'
nvim +'CocInstall coc-diagnostic'
nvim +'CocInstall coc-eslint'
nvim +'CocInstall coc-explorer'
nvim +'CocInstall coc-fzf-preview'
nvim +'CocInstall coc-git'
nvim +'CocInstall coc-highlight'
nvim +'CocInstall coc-html'
nvim +'CocInstall coc-json'
nvim +'CocInstall coc-markdownlint'
nvim +'CocInstall coc-pairs'
nvim +'CocInstall coc-phpls'
nvim +'CocInstall coc-prettier'
nvim +'CocInstall coc-pyright'
nvim +'CocInstall coc-rls'
nvim +'CocInstall coc-rust-analyzer'
nvim +'CocInstall coc-sh'
nvim +'CocInstall coc-spell-checker'
nvim +'CocInstall coc-cspell-dicts'
nvim +'CocInstall coc-tsserver'
nvim +'CocInstall coc-vetur'
nvim +'CocInstall coc-xml'
nvim +'CocInstall coc-yaml'

