# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$monitor_left = DP-1
#$monitor_right = DP-3

$filemanager = thunar
$applauncher = bemenu-run -in --tb "##2d2d2d" --tf "##cccccc" --fb "##515151" --ff "##cccccc" --nb "##2d2d2d" --nf "##cccccc" --hb "##2d2d2d" --hf "##99cc99" --fn "Hack 16"
$terminal = foot
$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'
$capturing = grim -g "$(slurp)" - | swappy -f -
