# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24

envd = GDK_DPI_SCALE,1.75
envd = QT_SCALE_FACTOR,1.75
envd = LIBVA_DRIVER_NAME,nvidia
envd = XDG_SESSION_TYPE,wayland
envd = GBM_BACKEND,nvidia-drm
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia
envd = __GL_GSYNC_ALLOWED,1
envd = __GL_VRR_ALLOWED,1

envd = QT_QPA_PLATFORMTHEME,qt6ct
envd = ELECTRON_OZONE_PLATFORM_HINT,auto
