# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/0.45.0/Configuring/Variables/#input

input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle,grp_led:scroll
    numlock_by_default = true

    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2

    touchpad {
        natural_scroll = false
    }

    accel_profile = flat
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}
