#!/usr/bin/env zsh
#
# .zshrc
# Copyright (C) 2016 real <real93@live.ru>
#
# Distributed under terms of the MIT license.
#

# cd to zshrc
pushd $(dirname $(readlink -f ~/.zshrc)) > /dev/null

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
# ctrl+w don't delete all to near space
WORDCHARS=''@""

zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true
zstyle ':completion::complete:*' use-cache 1

autoload -U compinit promptinit colors
colors
compinit
promptinit; prompt gentoo

for file in conf.d/*sh; do
    source $file
done

popd > /dev/null

GIT_PROMPT_EXECUTABLE="haskell"
export ANTIGEN_HS_OUT="$HOME/.zsh/plugins/workdir"
source $HOME/.zsh/plugins/antigen-hs/init.zsh

# TODO: rewrite more gracefull
export PROMPT=\
"$BOLD_START"\
"$FOREGROUND_START{blue}
┌─────────────────"\
"$FOREGROUND_STOP"\
"%(0?.$FOREGROUND_START{green}☺.$FOREGROUND_START{red}$LAST_RETURN_STATUS)"\
"$FOREGROUND_START{blue}
├ $CURRENT_DIR_REPLACE_HOME "\
"$FOREGROUND_STOP"\
'$(git_super_status)'\
"$FOREGROUND_START{blue}
└─%(!.$FOREGROUND_START{red}.$FOREGROUND_START{green})"\
"$USER_NAME@$MACHINE_HOSTNAME_FULL "\
"$FOREGROUND_STOP"\
"$FOREGROUND_START{blue}"\
"$PRIVILEGES_SIGN "\
"$FOREGROUND_STOP"\
"$BOLD_STOP"

# startx if we login on tty6
[[ "$(tty)" = "/dev/tty6" ]] && exec startx

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

FZF_TMUX=1
FZF_TMUX_HEIGHT='30%'

if [ -z "$TMUX" ]; then
    tmux attach
fi
